fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    registration:
        confirmation:
            enabled: false
    from_email:
        address: "mister.tzu@gmail.com"
        sender_name: "mister.tzu@gmail.com"
    service:
        mailer: fos_user.mailer.noop