version: '2'
services:
    onepolis:
        build:
            context: ./php_apache
        volumes:
            - .:/var/www/html
            - ./logs/html/:/var/www/html/app/logs/
        links:
            - mysql
        ports:
            - "6080:8000"
        container_name: onepolis
    mysql:
        image: mysql:5.7
        restart: always
        ports:
            - "6306:3306"
        environment:
          MYSQL_ROOT_PASSWORD: example
        volumes:
            - ./mysql_data:/var/lib/mysql    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
          - 6081:80
        environment:
          PMA_HOST: mysql
          MYSQL_ROOT_PASSWORD: example      